// models/UserProfile.js - Kullanıcı profil ve öğrenme modeli

const mongoose = require('mongoose');

// Kullanıcı davranış modeli
const userBehaviorSchema = new mongoose.Schema({
  // Temel bilgiler
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    unique: true
  },
  
  // Kişilik profili
  personality: {
    communicationStyle: {
      type: String,
      enum: ['formal', 'casual', 'friendly', 'technical', 'mixed'],
      default: 'mixed'
    },
    responsePreference: {
      type: String,
      enum: ['short', 'detailed', 'examples', 'step-by-step'],
      default: 'detailed'
    },
    learningStyle: {
      type: String,
      enum: ['visual', 'practical', 'theoretical', 'mixed'],
      default: 'mixed'
    }
  },
  
  // İlgi alanları ve konular
  interests: {
    primaryTopics: [{
      topic: String,
      count: { type: Number, default: 1 },
      lastAsked: { type: Date, default: Date.now }
    }],
    technicalLevel: {
      programming: { type: Number, min: 1, max: 10, default: 5 },
      technology: { type: Number, min: 1, max: 10, default: 5 },
      general: { type: Number, min: 1, max: 10, default: 5 }
    },
    preferredLanguages: [{
      language: String,
      proficiency: { type: Number, min: 1, max: 10, default: 5 }
    }]
  },
  
  // Konuşma kalıpları
  conversationPatterns: {
    averageMessageLength: { type: Number, default: 50 },
    questionTypes: [{
      type: { type: String }, // how, what, why, when, where
      frequency: { type: Number, default: 1 }
    }],
    commonWords: [{
      word: String,
      frequency: { type: Number, default: 1 }
    }],
    timePatterns: {
      mostActiveHours: [{ type: Number }], // 0-23 saat
      sessionDuration: { type: Number, default: 15 }, // dakika
      messagesPerSession: { type: Number, default: 5 }
    }
  },
  
  // Geri bildirim kalıpları
  feedbackPatterns: {
    helpfulnessRate: { type: Number, default: 0.7 }, // 0-1 arası
    averageRating: { type: Number, default: 3.5 }, // 1-5 arası
    commonComplaints: [{
      complaint: String,
      frequency: { type: Number, default: 1 }
    }],
    commonPraises: [{
      praise: String,
      frequency: { type: Number, default: 1 }
    }]
  },
  
  // Öğrenme ilerlemesi
  learningProgress: {
    topicsLearned: [{
      topic: String,
      level: { type: Number, min: 1, max: 10, default: 1 },
      lastUpdated: { type: Date, default: Date.now }
    }],
    skillDevelopment: [{
      skill: String,
      startLevel: { type: Number, default: 1 },
      currentLevel: { type: Number, default: 1 },
      progressRate: { type: Number, default: 0 }
    }],
    goals: [{
      goal: String,
      targetDate: Date,
      progress: { type: Number, default: 0 }, // 0-100%
      isAchieved: { type: Boolean, default: false }
    }]
  },
  
  // Sosyal özellikler
  socialProfile: {
    helpfulness: { type: Number, default: 5 }, // Başkalarına ne kadar yardımcı
    collaboration: { type: Number, default: 5 }, // İşbirliği seviyesi
    sharePreference: { type: Boolean, default: false }, // Bilgi paylaşımı istiyor mu
    mentorshipInterest: { type: Boolean, default: false } // Mentorluk ilgisi
  },
  
  // İstatistikler
  statistics: {
    totalMessages: { type: Number, default: 0 },
    totalSessions: { type: Number, default: 0 },
    totalFeedback: { type: Number, default: 0 },
    joinDate: { type: Date, default: Date.now },
    lastActive: { type: Date, default: Date.now },
    longestStreak: { type: Number, default: 0 }, // En uzun günlük kullanım serisi
    currentStreak: { type: Number, default: 0 }
  },
  
  // Kişiselleştirme ayarları
  preferences: {
    notificationPreference: {
      learningReminders: { type: Boolean, default: true },
      progressUpdates: { type: Boolean, default: true },
      personalizedSuggestions: { type: Boolean, default: true }
    },
    privacySettings: {
      allowDataCollection: { type: Boolean, default: true },
      allowPersonalization: { type: Boolean, default: true },
      shareAnonymousData: { type: Boolean, default: false }
    }
  },
  
  // Sistem tarafından otomatik güncellenen alanlar
  autoGenerated: {
    lastAnalysis: { type: Date, default: Date.now },
    profileCompleteness: { type: Number, default: 0 }, // 0-100%
    personalityScore: {
      extraversion: { type: Number, default: 50 }, // 0-100
      openness: { type: Number, default: 50 },
      conscientiousness: { type: Number, default: 50 }
    },
    nextRecommendedAction: {
      action: String,
      reason: String,
      priority: { type: Number, default: 1 }
    }
  }
}, {
  timestamps: true
});

// İndeksler
userBehaviorSchema.index({ userId: 1 });
userBehaviorSchema.index({ 'interests.primaryTopics.topic': 1 });
userBehaviorSchema.index({ 'statistics.lastActive': -1 });

// Profil güncellemesi için metodlar
userBehaviorSchema.methods.updateInterests = function(topic) {
  const existing = this.interests.primaryTopics.find(t => t.topic === topic);
  if (existing) {
    existing.count += 1;
    existing.lastAsked = new Date();
  } else {
    this.interests.primaryTopics.push({
      topic: topic,
      count: 1,
      lastAsked: new Date()
    });
  }
  
  // En fazla 20 konu tutulsun
  this.interests.primaryTopics = this.interests.primaryTopics
    .sort((a, b) => b.count - a.count)
    .slice(0, 20);
};

userBehaviorSchema.methods.updateConversationPattern = function(message) {
  // Mesaj uzunluğu ortalamasını güncelle
  const currentAvg = this.conversationPatterns.averageMessageLength;
  const messageCount = this.statistics.totalMessages;
  this.conversationPatterns.averageMessageLength = 
    ((currentAvg * messageCount) + message.length) / (messageCount + 1);
  
  // Soru türlerini analiz et
  const questionWords = ['nasıl', 'nedir', 'neden', 'ne zaman', 'nerede', 'kim', 'hangi'];
  questionWords.forEach(word => {
    if (message.toLowerCase().includes(word)) {
      const existing = this.conversationPatterns.questionTypes.find(q => q.type === word);
      if (existing) {
        existing.frequency += 1;
      } else {
        this.conversationPatterns.questionTypes.push({ type: word, frequency: 1 });
      }
    }
  });
};

userBehaviorSchema.methods.updateFeedbackPattern = function(isHelpful, rating, feedbackText) {
  // Yardımcılık oranını güncelle
  const totalFeedback = this.statistics.totalFeedback;
  const currentRate = this.feedbackPatterns.helpfulnessRate;
  const newHelpfulCount = (currentRate * totalFeedback) + (isHelpful ? 1 : 0);
  this.feedbackPatterns.helpfulnessRate = newHelpfulCount / (totalFeedback + 1);
  
  // Ortalama puanı güncelle
  if (rating) {
    const currentAvg = this.feedbackPatterns.averageRating;
    this.feedbackPatterns.averageRating = 
      ((currentAvg * totalFeedback) + rating) / (totalFeedback + 1);
  }
  
  // Geri bildirim metnini analiz et
  if (feedbackText && feedbackText.length > 5) {
    if (!isHelpful) {
      // Şikayetleri kaydet
      const existing = this.feedbackPatterns.commonComplaints.find(c => 
        c.complaint.toLowerCase().includes(feedbackText.toLowerCase().substring(0, 10))
      );
      if (existing) {
        existing.frequency += 1;
      } else {
        this.feedbackPatterns.commonComplaints.push({
          complaint: feedbackText.substring(0, 100),
          frequency: 1
        });
      }
    } else {
      // Övgüleri kaydet
      const existing = this.feedbackPatterns.commonPraises.find(p => 
        p.praise.toLowerCase().includes(feedbackText.toLowerCase().substring(0, 10))
      );
      if (existing) {
        existing.frequency += 1;
      } else {
        this.feedbackPatterns.commonPraises.push({
          praise: feedbackText.substring(0, 100),
          frequency: 1
        });
      }
    }
  }
};

userBehaviorSchema.methods.getPersonalizedPrompt = function() {
  let prompt = "Sen kişiselleştirilmiş bir AI asistanısın. ";
  
  // İletişim tarzına göre
  switch (this.personality.communicationStyle) {
    case 'formal':
      prompt += "Resmi ve saygılı bir dil kullan. ";
      break;
    case 'casual':
      prompt += "Samimi ve rahat bir dil kullan. ";
      break;
    case 'friendly':
      prompt += "Arkadaşça ve sıcak bir dil kullan. ";
      break;
    case 'technical':
      prompt += "Teknik ve detaylı açıklamalar yap. ";
      break;
  }
  
  // Yanıt tercihine göre
  switch (this.personality.responsePreference) {
    case 'short':
      prompt += "Kısa ve öz yanıtlar ver. ";
      break;
    case 'detailed':
      prompt += "Detaylı ve kapsamlı açıklamalar yap. ";
      break;
    case 'examples':
      prompt += "Bol örnek kullan. ";
      break;
    case 'step-by-step':
      prompt += "Adım adım açıklamalar yap. ";
      break;
  }
  
  // İlgi alanlarına göre
  if (this.interests.primaryTopics.length > 0) {
    const topTopics = this.interests.primaryTopics.slice(0, 3).map(t => t.topic);
    prompt += `Kullanıcının ana ilgi alanları: ${topTopics.join(', ')}. Bu konularda daha detaylı ol. `;
  }
  
  // Teknik seviyeye göre
  const techLevel = this.interests.technicalLevel.programming;
  if (techLevel <= 3) {
    prompt += "Teknik konuları basit terimlerle açıkla. ";
  } else if (techLevel >= 8) {
    prompt += "İleri seviye teknik detaylara girebilirsin. ";
  }
  
  return prompt;
};

const UserProfile = mongoose.model('UserProfile', userBehaviorSchema);

module.exports = UserProfile;